using Simplices, SimplexSplitting, InvariantDistribution

@testset "Markov matrix discrete dense" begin

    t = triang_from_embedding(
            Embedding(
                invariant_gaussian_embedding(npts = 15, covariance = 0.3, tau = 1)
            )
        )
    # Estimate markov matrices using the two available methods: using randomly
    # distributed points or uniformly distributed points generated by
    # shape-preserving splitting of the simplices.
    M1= mm_dd(t, sample_randomly = false)
    M2 = mm_dd(t, sample_randomly = true)
    @test all(sum(M1, 2) .≈ 1)
    @test all(sum(M2, 2) .≈ 1)
end
